- name: Base configuration
  hosts: all
  become: true
  roles:
    - common
    - gitlab-runner

- name: K3s install
  hosts: k3s_server
  become: true
  roles:
    - k3s

- name: Docker install
  hosts: runner_build
  become: true
  roles:
    - docker